/**
 * Generated by tools/screen_compiler/battle_compile.py.
 * Do not edit directly -- edit screens/combat_art/ and re-run.
 * Fixed bank (no pragma): read by the bank-4 art loader.
 */

#include <stdint.h>

/* OBJ ramps for OAM battle art. Indexed by g_battle_art_obj. */
const uint8_t g_battle_obj_ramps[] = {
    /* fightslime */ 0xFF, 0x7F, 0x31, 0x2F, 0x4B, 0x1E, 0x00, 0x00,
    /* fightbat */ 0xFF, 0x7F, 0xC7, 0x20, 0x71, 0x0C, 0x00, 0x00,
    /* sprites6 */ 0xBE, 0x03, 0xD1, 0x25, 0x6D, 0x19, 0xC7, 0x08,
    /* fightgoblin */ 0xFF, 0x7F, 0x30, 0x25, 0x89, 0x10, 0x89, 0x10,
    /* fightspider */ 0xFF, 0x7F, 0x31, 0x46, 0x2B, 0x1D, 0x00, 0x00,
};
/* Per art set (art_order): OBJ ramp index, or 0xFF = BG stamp. */
const uint8_t g_battle_art_obj[] = {0x00, 0x01, 0xFF, 0x02, 0x03, 0x04};
/* Per art set (art_order): second OBJ ramp index for off-ramp
 * cells (spider eye), or 0xFF = none.  Programmed into
 * BATTLE_OBJ_SCRATCH2 at battle entry (bank-5 alt loader). */
const uint8_t g_battle_art_obj_alt[] = {0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0x01};
/* Per art set (art_order): frame-relative cell bitmask drawn
 * with the alt ramp (uint8: width*height must be <= 8). */
const uint8_t g_battle_art_alt_mask[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x02};

