/**
 * Generated by tools/screen_compiler/battle_compile.py.
 * Do not edit directly -- edit screens/combat_art/ and re-run.
 * Bank 5: read by the bank-5 battle OAM pass.
 */

#pragma bank 5

#include <stdint.h>

/* Eye-glow ramp bytes (CGB order, low first). Indexed by
 * g_battle_art_glow_unlit/lit below. */
const uint8_t g_battle_glow_ramps[] = {
    /* fightboss2 */ 0xFF, 0x7F, 0x71, 0x0C, 0x4A, 0x29, 0x00, 0x00,
    /* fightboss3 */ 0xFF, 0x7F, 0xDE, 0x19, 0x4A, 0x29, 0x00, 0x00,
};
/* Per art set (art_order): overlay eye-cell bitmask
 * (frame0-relative row-major indices, all < 6: one OAM
 * stride per enemy slot). */
const uint8_t g_battle_art_glow_mask[] = {0x00, 0x00, 0x18, 0x00, 0x00, 0x00};
/* Per art set (art_order): unlit/lit ramp indices into
 * g_battle_glow_ramps above (0xFF = no overlay). Programmed
 * into the battle scratch OBJ slots at battle entry. */
const uint8_t g_battle_art_glow_unlit[] = {0xFF, 0xFF, 0x00, 0xFF, 0xFF, 0xFF};
const uint8_t g_battle_art_glow_lit[] = {0xFF, 0xFF, 0x01, 0xFF, 0xFF, 0xFF};

