/**
 * Generated by tools/screen_compiler/battle_compile.py --all.
 * Do not edit directly -- edit screens/rider_icons.json and re-run.
 * Battle per-card OAM rider icons: VRAM tile ids + OBJ palette slots
 * for the selected-card element riders.
 */

#ifndef RIDER_TILES_GENERATED_H
#define RIDER_TILES_GENERATED_H

#define RIDER_TILE_BURN 120
#define RIDER_OBJ_BURN 4
#define RIDER_TILE_FREEZE 121
#define RIDER_OBJ_FREEZE 2
#define RIDER_TILE_POISON 122
#define RIDER_OBJ_POISON 2

#endif /* RIDER_TILES_GENERATED_H */
