/* Generated by tools/level_compiler/compile.py -- DO NOT EDIT DIRECTLY */
#pragma bank 7

#include "scene.h"
#include "banked.h"

/* ── Overflow scene terrain (bank 5 is exhausted) ──────
 * Stamped by terrain_stamp_b<N>_banked() below, dispatched
 * by scene_load_tiles() (see scene.c). Arrays stay static:
 * reader and data share this bank, nothing references
 * them from outside.
 */

const SceneTerrainBlock s_village_area_terrain[] = {
    { 0, 0, 1, 1, TILE_VILLAGE_00 },
    { 1, 0, 8, 1, TILE_VILLAGE_01 },
    { 9, 0, 2, 2, TILE_VILLAGE_06 },
    { 11, 0, 8, 1, TILE_VILLAGE_01 },
    { 19, 0, 1, 1, TILE_VILLAGE_02 },
    { 0, 1, 1, 7, TILE_VILLAGE_19 },
    { 19, 1, 1, 7, TILE_VILLAGE_03 },
    { 1, 2, 1, 1, TILE_VILLAGE_20 },
    { 2, 2, 1, 1, TILE_VILLAGE_07 },
    { 3, 2, 1, 1, TILE_VILLAGE_08 },
    { 5, 2, 1, 1, TILE_VILLAGE_37 },
    { 8, 2, 1, 1, TILE_VILLAGE_20 },
    { 10, 2, 1, 1, TILE_VILLAGE_20 },
    { 2, 3, 1, 1, TILE_VILLAGE_23 },
    { 3, 3, 1, 1, TILE_VILLAGE_24 },
    { 4, 3, 1, 1, TILE_VILLAGE_21 },
    { 7, 3, 1, 1, TILE_VILLAGE_13 },
    { 8, 3, 1, 1, TILE_VILLAGE_14 },
    { 9, 3, 1, 1, TILE_VILLAGE_15 },
    { 12, 3, 1, 1, TILE_VILLAGE_36 },
    { 15, 3, 1, 1, TILE_VILLAGE_20 },
    { 17, 3, 1, 1, TILE_VILLAGE_21 },
    { 4, 4, 1, 1, TILE_VILLAGE_20 },
    { 7, 4, 1, 1, TILE_VILLAGE_29 },
    { 8, 4, 1, 1, TILE_VILLAGE_30 },
    { 9, 4, 1, 1, TILE_VILLAGE_31 },
    { 14, 4, 1, 1, TILE_VILLAGE_10 },
    { 15, 4, 1, 1, TILE_VILLAGE_11 },
    { 16, 4, 1, 1, TILE_VILLAGE_12 },
    { 18, 4, 1, 1, TILE_VILLAGE_20 },
    { 2, 5, 1, 1, TILE_VILLAGE_20 },
    { 6, 5, 1, 1, TILE_VILLAGE_22 },
    { 7, 5, 1, 1, TILE_VILLAGE_42 },
    { 8, 5, 1, 1, TILE_VILLAGE_43 },
    { 9, 5, 1, 1, TILE_VILLAGE_44 },
    { 14, 5, 1, 1, TILE_VILLAGE_26 },
    { 15, 5, 1, 1, TILE_VILLAGE_27 },
    { 16, 5, 1, 1, TILE_VILLAGE_28 },
    { 3, 6, 1, 1, TILE_VILLAGE_13 },
    { 4, 6, 1, 1, TILE_VILLAGE_14 },
    { 5, 6, 1, 1, TILE_VILLAGE_15 },
    { 6, 6, 1, 1, TILE_VILLAGE_20 },
    { 13, 6, 1, 1, TILE_VILLAGE_20 },
    { 14, 6, 1, 1, TILE_VILLAGE_42 },
    { 15, 6, 1, 1, TILE_VILLAGE_43 },
    { 16, 6, 1, 1, TILE_VILLAGE_44 },
    { 17, 6, 1, 1, TILE_VILLAGE_22 },
    { 3, 7, 1, 1, TILE_VILLAGE_29 },
    { 4, 7, 1, 1, TILE_VILLAGE_30 },
    { 5, 7, 1, 1, TILE_VILLAGE_31 },
    { 17, 7, 1, 1, TILE_VILLAGE_21 },
    { 0, 8, 3, 2, TILE_VILLAGE_06 },
    { 3, 8, 1, 1, TILE_VILLAGE_42 },
    { 4, 8, 1, 1, TILE_VILLAGE_43 },
    { 5, 8, 1, 1, TILE_VILLAGE_44 },
    { 6, 8, 1, 1, TILE_VILLAGE_21 },
    { 8, 8, 1, 1, TILE_VILLAGE_35 },
    { 19, 8, 1, 2, TILE_VILLAGE_06 },
    { 4, 9, 1, 1, TILE_VILLAGE_20 },
    { 13, 9, 1, 1, TILE_VILLAGE_20 },
    { 14, 9, 1, 1, TILE_VILLAGE_37 },
    { 15, 9, 1, 1, TILE_VILLAGE_41 },
    { 0, 10, 1, 7, TILE_VILLAGE_19 },
    { 19, 10, 1, 7, TILE_VILLAGE_03 },
    { 2, 11, 1, 1, TILE_VILLAGE_13 },
    { 3, 11, 1, 1, TILE_VILLAGE_14 },
    { 4, 11, 1, 1, TILE_VILLAGE_15 },
    { 6, 11, 1, 1, TILE_VILLAGE_20 },
    { 8, 11, 1, 1, TILE_VILLAGE_22 },
    { 2, 12, 1, 1, TILE_VILLAGE_29 },
    { 3, 12, 1, 1, TILE_VILLAGE_30 },
    { 4, 12, 1, 1, TILE_VILLAGE_31 },
    { 8, 12, 1, 1, TILE_VILLAGE_20 },
    { 9, 12, 1, 1, TILE_VILLAGE_10 },
    { 10, 12, 1, 1, TILE_VILLAGE_11 },
    { 11, 12, 1, 1, TILE_VILLAGE_12 },
    { 15, 12, 1, 1, TILE_VILLAGE_20 },
    { 2, 13, 1, 1, TILE_VILLAGE_42 },
    { 3, 13, 1, 1, TILE_VILLAGE_43 },
    { 4, 13, 1, 1, TILE_VILLAGE_44 },
    { 5, 13, 1, 1, TILE_VILLAGE_22 },
    { 9, 13, 1, 1, TILE_VILLAGE_26 },
    { 10, 13, 1, 1, TILE_VILLAGE_27 },
    { 11, 13, 1, 1, TILE_VILLAGE_28 },
    { 13, 13, 1, 1, TILE_VILLAGE_07 },
    { 14, 13, 1, 1, TILE_VILLAGE_08 },
    { 16, 13, 1, 1, TILE_VILLAGE_39 },
    { 2, 14, 1, 1, TILE_VILLAGE_20 },
    { 5, 14, 1, 1, TILE_VILLAGE_20 },
    { 8, 14, 1, 1, TILE_VILLAGE_04 },
    { 9, 14, 1, 1, TILE_VILLAGE_42 },
    { 10, 14, 1, 1, TILE_VILLAGE_43 },
    { 11, 14, 1, 1, TILE_VILLAGE_44 },
    { 12, 14, 1, 1, TILE_VILLAGE_21 },
    { 13, 14, 1, 1, TILE_VILLAGE_23 },
    { 14, 14, 1, 1, TILE_VILLAGE_24 },
    { 17, 14, 1, 1, TILE_VILLAGE_20 },
    { 13, 15, 1, 1, TILE_VILLAGE_20 },
    { 1, 16, 1, 1, TILE_VILLAGE_21 },
    { 4, 16, 1, 1, TILE_VILLAGE_37 },
    { 17, 16, 1, 1, TILE_VILLAGE_21 },
    { 0, 17, 1, 1, TILE_VILLAGE_16 },
    { 1, 17, 18, 1, TILE_VILLAGE_17 },
    { 19, 17, 1, 1, TILE_VILLAGE_18 },
    { 0, 0, 0, 0, 0 }
};

/* Terrain stamp body for bank 7: array address arrives
 * in g_bk_ptr_b, the World in g_bk_ptr_a. Self-contained:
 * no fixed-bank calls (same rule as scene_load_tiles_banked).
 * Bounds checks are omitted deliberately: validate.py fails
 * loudly on out-of-bounds terrain blocks, so committed
 * content always fits (the home body keeps its own clamps). */
void terrain_stamp_b7_banked(void)
{
    World *w = (World *)g_bk_ptr_a;
    const SceneTerrainBlock *b = (const SceneTerrainBlock *)g_bk_ptr_b;
    uint8_t x, y;

    if (!w) return;
    for ( ; ; b++) {
        if (b->w == 0) break;
        for (y = b->y; y < (uint8_t)(b->y + b->h); y++) {
            uint8_t *row = w->map[y];
            for (x = b->x; x < (uint8_t)(b->x + b->w); x++) {
                row[x] = b->tile;
            }
        }
    }
}

