/* Generated by tools/level_compiler/compile.py -- DO NOT EDIT DIRECTLY */
#pragma bank 6

#include "scene.h"
#include "banked.h"

/* ── Overflow scene terrain (bank 5 is exhausted) ──────
 * Stamped by terrain_stamp_b<N>_banked() below, dispatched
 * by scene_load_tiles() (see scene.c). Arrays stay static:
 * reader and data share this bank, nothing references
 * them from outside.
 */

const SceneTerrainBlock s_desolate_field_terrain[] = {
    { 0, 0, 20, 2, TILE_DESOLATE_LANDSCAPE_32 },
    { 0, 2, 9, 2, TILE_DESOLATE_LANDSCAPE_32 },
    { 9, 2, 1, 1, TILE_DESOLATE_LANDSCAPE_00 },
    { 10, 2, 1, 1, TILE_DESOLATE_LANDSCAPE_02 },
    { 11, 2, 1, 1, TILE_DESOLATE_LANDSCAPE_04 },
    { 12, 2, 1, 1, TILE_DESOLATE_LANDSCAPE_02 },
    { 13, 2, 1, 1, TILE_DESOLATE_LANDSCAPE_03 },
    { 14, 2, 1, 1, TILE_DESOLATE_LANDSCAPE_02 },
    { 15, 2, 1, 1, TILE_DESOLATE_LANDSCAPE_03 },
    { 16, 2, 1, 1, TILE_DESOLATE_LANDSCAPE_02 },
    { 17, 2, 1, 1, TILE_DESOLATE_LANDSCAPE_04 },
    { 18, 2, 1, 1, TILE_DESOLATE_LANDSCAPE_05 },
    { 19, 2, 1, 1, TILE_DESOLATE_LANDSCAPE_32 },
    { 9, 3, 1, 1, TILE_DESOLATE_LANDSCAPE_27 },
    { 10, 3, 8, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 18, 3, 1, 1, TILE_DESOLATE_LANDSCAPE_33 },
    { 19, 3, 1, 1, TILE_DESOLATE_LANDSCAPE_05 },
    { 0, 4, 4, 1, TILE_DESOLATE_LANDSCAPE_32 },
    { 4, 4, 1, 1, TILE_DESOLATE_LANDSCAPE_00 },
    { 5, 4, 1, 1, TILE_DESOLATE_LANDSCAPE_02 },
    { 6, 4, 1, 1, TILE_DESOLATE_LANDSCAPE_04 },
    { 7, 4, 1, 1, TILE_DESOLATE_LANDSCAPE_03 },
    { 8, 4, 1, 1, TILE_DESOLATE_LANDSCAPE_02 },
    { 9, 4, 1, 1, TILE_DESOLATE_LANDSCAPE_34 },
    { 10, 4, 1, 7, TILE_DESOLATE_LANDSCAPE_41 },
    { 11, 4, 1, 1, TILE_DESOLATE_LANDSCAPE_14 },
    { 12, 4, 1, 1, TILE_DESOLATE_LANDSCAPE_15 },
    { 13, 4, 6, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 19, 4, 1, 1, TILE_DESOLATE_LANDSCAPE_08 },
    { 0, 5, 1, 1, TILE_DESOLATE_LANDSCAPE_00 },
    { 1, 5, 1, 1, TILE_DESOLATE_LANDSCAPE_01 },
    { 2, 5, 1, 1, TILE_DESOLATE_LANDSCAPE_03 },
    { 3, 5, 1, 1, TILE_DESOLATE_LANDSCAPE_02 },
    { 4, 5, 1, 1, TILE_DESOLATE_LANDSCAPE_34 },
    { 5, 5, 5, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 11, 5, 1, 1, TILE_DESOLATE_LANDSCAPE_30 },
    { 12, 5, 1, 1, TILE_DESOLATE_LANDSCAPE_31 },
    { 13, 5, 1, 6, TILE_DESOLATE_LANDSCAPE_41 },
    { 14, 5, 1, 1, TILE_DESOLATE_LANDSCAPE_12 },
    { 15, 5, 1, 1, TILE_DESOLATE_LANDSCAPE_13 },
    { 16, 5, 3, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 19, 5, 1, 1, TILE_DESOLATE_LANDSCAPE_06 },
    { 0, 6, 1, 1, TILE_DESOLATE_LANDSCAPE_27 },
    { 1, 6, 6, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 7, 6, 1, 1, TILE_DESOLATE_LANDSCAPE_21 },
    { 8, 6, 2, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 11, 6, 2, 10, TILE_DESOLATE_LANDSCAPE_41 },
    { 14, 6, 1, 1, TILE_DESOLATE_LANDSCAPE_28 },
    { 15, 6, 1, 1, TILE_DESOLATE_LANDSCAPE_29 },
    { 16, 6, 1, 2, TILE_DESOLATE_LANDSCAPE_41 },
    { 17, 6, 1, 1, TILE_DESOLATE_LANDSCAPE_21 },
    { 18, 6, 1, 4, TILE_DESOLATE_LANDSCAPE_41 },
    { 19, 6, 1, 1, TILE_DESOLATE_LANDSCAPE_07 },
    { 0, 7, 1, 1, TILE_DESOLATE_LANDSCAPE_10 },
    { 1, 7, 1, 3, TILE_DESOLATE_LANDSCAPE_41 },
    { 2, 7, 1, 1, TILE_DESOLATE_LANDSCAPE_12 },
    { 3, 7, 1, 1, TILE_DESOLATE_LANDSCAPE_13 },
    { 4, 7, 4, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 8, 7, 1, 1, TILE_DESOLATE_LANDSCAPE_21 },
    { 9, 7, 1, 6, TILE_DESOLATE_LANDSCAPE_41 },
    { 14, 7, 2, 6, TILE_DESOLATE_LANDSCAPE_41 },
    { 17, 7, 1, 3, TILE_DESOLATE_LANDSCAPE_41 },
    { 19, 7, 1, 1, TILE_DESOLATE_LANDSCAPE_25 },
    { 0, 8, 1, 1, TILE_DESOLATE_LANDSCAPE_11 },
    { 2, 8, 1, 1, TILE_DESOLATE_LANDSCAPE_28 },
    { 3, 8, 1, 1, TILE_DESOLATE_LANDSCAPE_29 },
    { 4, 8, 1, 2, TILE_DESOLATE_LANDSCAPE_41 },
    { 5, 8, 1, 1, TILE_DESOLATE_LANDSCAPE_24 },
    { 6, 8, 3, 2, TILE_DESOLATE_LANDSCAPE_41 },
    { 16, 8, 1, 1, TILE_DESOLATE_LANDSCAPE_22 },
    { 19, 8, 1, 1, TILE_DESOLATE_LANDSCAPE_33 },
    { 0, 9, 1, 1, TILE_DESOLATE_LANDSCAPE_09 },
    { 2, 9, 2, 4, TILE_DESOLATE_LANDSCAPE_41 },
    { 5, 9, 1, 3, TILE_DESOLATE_LANDSCAPE_41 },
    { 16, 9, 1, 4, TILE_DESOLATE_LANDSCAPE_41 },
    { 19, 9, 1, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 0, 10, 1, 1, TILE_DESOLATE_LANDSCAPE_16 },
    { 1, 10, 1, 1, TILE_DESOLATE_LANDSCAPE_35 },
    { 4, 10, 1, 1, TILE_DESOLATE_LANDSCAPE_21 },
    { 6, 10, 1, 2, TILE_DESOLATE_LANDSCAPE_41 },
    { 7, 10, 1, 1, TILE_DESOLATE_LANDSCAPE_22 },
    { 8, 10, 1, 5, TILE_DESOLATE_LANDSCAPE_41 },
    { 17, 10, 1, 1, TILE_DESOLATE_LANDSCAPE_24 },
    { 18, 10, 1, 1, TILE_DESOLATE_LANDSCAPE_36 },
    { 19, 10, 1, 1, TILE_DESOLATE_LANDSCAPE_20 },
    { 0, 11, 1, 7, TILE_DESOLATE_LANDSCAPE_32 },
    { 1, 11, 1, 1, TILE_DESOLATE_LANDSCAPE_11 },
    { 4, 11, 1, 4, TILE_DESOLATE_LANDSCAPE_41 },
    { 7, 11, 1, 4, TILE_DESOLATE_LANDSCAPE_41 },
    { 10, 11, 1, 1, TILE_DESOLATE_LANDSCAPE_21 },
    { 13, 11, 1, 1, TILE_DESOLATE_LANDSCAPE_21 },
    { 17, 11, 1, 5, TILE_DESOLATE_LANDSCAPE_41 },
    { 18, 11, 1, 1, TILE_DESOLATE_LANDSCAPE_07 },
    { 19, 11, 1, 2, TILE_DESOLATE_LANDSCAPE_32 },
    { 1, 12, 1, 1, TILE_DESOLATE_LANDSCAPE_09 },
    { 5, 12, 1, 1, TILE_DESOLATE_LANDSCAPE_14 },
    { 6, 12, 1, 1, TILE_DESOLATE_LANDSCAPE_15 },
    { 10, 12, 1, 6, TILE_DESOLATE_LANDSCAPE_41 },
    { 13, 12, 1, 2, TILE_DESOLATE_LANDSCAPE_41 },
    { 18, 12, 1, 1, TILE_DESOLATE_LANDSCAPE_25 },
    { 1, 13, 1, 1, TILE_DESOLATE_LANDSCAPE_10 },
    { 3, 13, 1, 1, TILE_DESOLATE_LANDSCAPE_24 },
    { 5, 13, 1, 1, TILE_DESOLATE_LANDSCAPE_30 },
    { 6, 13, 1, 1, TILE_DESOLATE_LANDSCAPE_31 },
    { 9, 13, 1, 1, TILE_DESOLATE_LANDSCAPE_21 },
    { 14, 13, 1, 3, TILE_DESOLATE_LANDSCAPE_41 },
    { 15, 13, 1, 1, TILE_DESOLATE_LANDSCAPE_12 },
    { 16, 13, 1, 1, TILE_DESOLATE_LANDSCAPE_13 },
    { 18, 13, 1, 1, TILE_DESOLATE_LANDSCAPE_33 },
    { 19, 13, 1, 1, TILE_DESOLATE_LANDSCAPE_05 },
    { 1, 14, 1, 1, TILE_DESOLATE_LANDSCAPE_27 },
    { 3, 14, 1, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 5, 14, 2, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 9, 14, 1, 2, TILE_DESOLATE_LANDSCAPE_41 },
    { 13, 14, 1, 1, TILE_DESOLATE_LANDSCAPE_22 },
    { 15, 14, 1, 1, TILE_DESOLATE_LANDSCAPE_28 },
    { 16, 14, 1, 1, TILE_DESOLATE_LANDSCAPE_29 },
    { 18, 14, 1, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 19, 14, 1, 1, TILE_DESOLATE_LANDSCAPE_08 },
    { 1, 15, 1, 1, TILE_DESOLATE_LANDSCAPE_16 },
    { 2, 15, 6, 1, TILE_DESOLATE_LANDSCAPE_20 },
    { 8, 15, 1, 1, TILE_DESOLATE_LANDSCAPE_35 },
    { 13, 15, 1, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 15, 15, 2, 1, TILE_DESOLATE_LANDSCAPE_41 },
    { 19, 15, 1, 1, TILE_DESOLATE_LANDSCAPE_07 },
    { 1, 16, 7, 2, TILE_DESOLATE_LANDSCAPE_32 },
    { 8, 16, 1, 1, TILE_DESOLATE_LANDSCAPE_16 },
    { 9, 16, 1, 1, TILE_DESOLATE_LANDSCAPE_35 },
    { 11, 16, 1, 2, TILE_DESOLATE_LANDSCAPE_41 },
    { 12, 16, 1, 1, TILE_DESOLATE_LANDSCAPE_36 },
    { 13, 16, 6, 1, TILE_DESOLATE_LANDSCAPE_20 },
    { 19, 16, 1, 1, TILE_DESOLATE_LANDSCAPE_26 },
    { 8, 17, 1, 1, TILE_DESOLATE_LANDSCAPE_32 },
    { 9, 17, 1, 1, TILE_DESOLATE_LANDSCAPE_09 },
    { 12, 17, 1, 1, TILE_DESOLATE_LANDSCAPE_07 },
    { 13, 17, 7, 1, TILE_DESOLATE_LANDSCAPE_32 },
    { 0, 0, 0, 0, 0 }
};

/* Terrain stamp body for bank 6: array address arrives
 * in g_bk_ptr_b, the World in g_bk_ptr_a. Self-contained:
 * no fixed-bank calls (same rule as scene_load_tiles_banked).
 * Bounds checks are omitted deliberately: validate.py fails
 * loudly on out-of-bounds terrain blocks, so committed
 * content always fits (the home body keeps its own clamps). */
void terrain_stamp_b6_banked(void)
{
    World *w = (World *)g_bk_ptr_a;
    const SceneTerrainBlock *b = (const SceneTerrainBlock *)g_bk_ptr_b;
    uint8_t x, y;

    if (!w) return;
    for ( ; ; b++) {
        if (b->w == 0) break;
        for (y = b->y; y < (uint8_t)(b->y + b->h); y++) {
            uint8_t *row = w->map[y];
            for (x = b->x; x < (uint8_t)(b->x + b->w); x++) {
                row[x] = b->tile;
            }
        }
    }
}

