/** Pipeline-exact ROM recolor for the level editor (client-side, live).
 *
 *  Ports tools/png2gb.py `nearest_shade` 1:1 so the browser preview shows
 *  exactly what the ROM will render:
 *    - exact pixel match against the ramp wins;
 *    - else the nearest shade WITHIN that ramp (Euclidean RGB);
 *    - transparent0 (whole `obj` set + battle OAM cells): pure white maps
 *      straight to shade 0 (sheet background, never a repaint todo) and any
 *      other off-ramp pixel falls back to the nearest of shades 1-3
 *      (index 0 stays reserved for exact background-key matches).
 *
 *  Ramps come from assets/palette_ramps.json (generated by
 *  tools/palette_compiler.py via `make manifest`, published to
 *  public/palette_ramps.json and fetched here at /palette_ramps.json).
 *  Results are cached per (image-src, ramp) so map panning stays fast.
 */

export interface RampEntry {
  colors: string[];
  refs: string[];
  slots: string[];
}

export interface RampGuide {
  ramps: Record<string, RampEntry>;
  slots: Record<string, Record<string, string>>;
  rules: Record<string, string>;
}

let guideCache: RampGuide | null = null;
let guidePromise: Promise<RampGuide> | null = null;

export async function fetchRampGuide(): Promise<RampGuide> {
  if (guideCache) return guideCache;
  if (!guidePromise) {
    guidePromise = fetch('/palette_ramps.json').then(async (res) => {
      if (!res.ok) throw new Error(`palette_ramps.json returned ${res.status}`);
      const body = (await res.json()) as RampGuide;
      if (!body.ramps) throw new Error('palette_ramps.json: want ramps');
      guideCache = body;
      return body;
    }).catch((e) => {
      guidePromise = null;
      throw e;
    });
  }
  return guidePromise;
}

export function rampColors(guide: RampGuide | null, name: string): string[] | null {
  const entry = guide?.ramps[name];
  return entry ? entry.colors : null;
}

export type Rgb = [number, number, number];

export const hexToRgb = (hex: string): Rgb => {
  const h = hex.replace('#', '');
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
};

const dist2 = (a: Rgb, b: Rgb): number =>
  (a[0] - b[0]) * (a[0] - b[0]) +
  (a[1] - b[1]) * (a[1] - b[1]) +
  (a[2] - b[2]) * (a[2] - b[2]);

const isWhite = (r: number, g: number, b: number): boolean =>
  r === 255 && g === 255 && b === 255;

/** Port of png2gb.nearest_shade for an ordered 4-ramp. */
export function nearestShadeIndex(
  r: number, g: number, b: number,
  ramp: Rgb[],
  transparent0: boolean,
): number {
  for (let i = 0; i < 4; i++) {
    const s = ramp[i];
    if (r === s[0] && g === s[1] && b === s[2]) return i;
  }
  if (transparent0 && isWhite(r, g, b)) return 0;
  let best = 0;
  let bestD: number | null = null;
  for (let i = 0; i < 4; i++) {
    if (transparent0 && i === 0) continue;
    const d = dist2([r, g, b], ramp[i]);
    if (bestD === null || d < bestD) {
      best = i;
      bestD = d;
    }
  }
  return best;
}

/** Recolor a loaded image's pixels through a ramp, returning a data URL.
 *  Transparent pixels (alpha < 128) pass through untouched. */
export function recoloredDataUrl(
  img: HTMLImageElement,
  colors: string[],
  transparent0 = false,
): string {
  if (!colors || colors.length !== 4) return img.src;
  const c = document.createElement('canvas');
  c.width = img.naturalWidth;
  c.height = img.naturalHeight;
  if (c.width === 0 || c.height === 0) return img.src;
  const ctx = c.getContext('2d');
  if (!ctx) return img.src;
  ctx.drawImage(img, 0, 0);
  let data: ImageData;
  try {
    data = ctx.getImageData(0, 0, c.width, c.height);
  } catch {
    return img.src;
  }
  const px = data.data;
  const ramp = colors.map(hexToRgb);
  for (let i = 0; i < px.length; i += 4) {
    if (px[i + 3] < 128) continue;
    const idx = nearestShadeIndex(px[i], px[i + 1], px[i + 2], ramp, transparent0);
    const t = ramp[idx];
    px[i] = t[0];
    px[i + 1] = t[1];
    px[i + 2] = t[2];
  }
  ctx.putImageData(data, 0, 0);
  return c.toDataURL();
}

/* Per-(src, ramp, transparency) data-URL cache so the map render loop
 * never recolors the same tile twice. */
const urlCache = new Map<string, string>();

export function cachedRecolorKey(src: string, colors: string[], transparent0: boolean): string {
  return `${src}|${colors.join(',')}|${transparent0 ? 't' : 'o'}`;
}

export function getCachedRecolor(src: string, colors: string[], transparent0: boolean): string | undefined {
  return urlCache.get(cachedRecolorKey(src, colors, transparent0));
}

export function setCachedRecolor(src: string, colors: string[], transparent0: boolean, url: string): void {
  // Bound the cache: ~600 tiles x a few ramps fits easily; drop oldest
  // when it grows past a generous cap so long sessions can't leak.
  if (urlCache.size > 4000) {
    const first = urlCache.keys().next();
    if (!first.done) urlCache.delete(first.value);
  }
  urlCache.set(cachedRecolorKey(src, colors, transparent0), url);
}

/** Load src, recolor through the ramp, resolve with a cached image element.
 *  Resolves with the ORIGINAL image when recoloring is impossible
 *  (opaque-art fallback: preview is then approximate, same as before). */
export function recoloredImage(
  src: string,
  colors: string[],
  transparent0 = false,
): Promise<HTMLImageElement> {
  const hit = getCachedRecolor(src, colors, transparent0);
  if (hit) {
    const img = new Image();
    img.src = hit;
    return new Promise((resolve) => {
      img.onload = () => resolve(img);
      img.onerror = () => resolve(img);
    });
  }
  return new Promise((resolve) => {
    const img = new Image();
    img.onload = () => {
      const url = recoloredDataUrl(img, colors, transparent0);
      if (url !== img.src) setCachedRecolor(src, colors, transparent0, url);
      if (url === img.src) {
        resolve(img);
        return;
      }
      const out = new Image();
      out.onload = () => resolve(out);
      out.onerror = () => resolve(img);
      out.src = url;
    };
    img.onerror = () => resolve(img);
    img.src = src;
  });
}
