#!/usr/bin/env python3
"""verify_ramp_tags.py -- Are the right ramps used?

Reads assets/palette_ramps.json (the single machine-readable ramp source,
generated by tools/palette_compiler.py via `make manifest`) and checks every
content ramp tag in one pass. Two modes:

  report (default): tag *validity* findings -- unknown ramp names, or tags
      naming ramps with no hardware slot in their set. Advisory only, always
      exits 0: the encoder's nearest-ramp fallback is by design (ramps win).

  --strict: mechanical facts, exits 1 on violation --
      * every VRAM-block world tile carries an explicit `palette` tag
        (no silent nearest-ramp fallback);
      * the committed assets/palette_ramps.json (+ public copy) matches a
        fresh render (run `make manifest` to refresh);
      * every generated/tiles/ramp_mismatches.json entry is covered by
        assets/ramp_mismatch_allowlist.json (no new fallbacks).

Tool breakage (unreadable inputs) exits 2 in both modes.

Usage (inside nix develop):
    python3 tools/verify_ramp_tags.py [--strict]
"""

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "tools"))

EXPORT = REPO_ROOT / "assets" / "palette_ramps.json"
EXPORT_PUBLIC = REPO_ROOT / "tools" / "level_editor" / "public" / "palette_ramps.json"
ALLOWLIST = REPO_ROOT / "assets" / "ramp_mismatch_allowlist.json"
MISMATCHES = REPO_ROOT / "generated" / "tiles" / "ramp_mismatches.json"
TILESETS_DIR = REPO_ROOT / "tools" / "level_editor" / "tilesets"

WORLD_SETS = ["forest", "castle", "desolate_landscape", "village"]


def load_json(path):
    try:
        return json.loads(Path(path).read_text())
    except OSError as e:
        raise ToolError(f"cannot read {path}: {e}")
    except ValueError as e:
        raise ToolError(f"{path}: invalid JSON: {e}")


class ToolError(Exception):
    pass


def check_world_tags(exp):
    """Returns (findings, untagged). findings are advisory validity rows;
    untagged are (set, tile) pairs missing a tag (strict errors)."""
    ramps = exp["ramps"]
    findings = []
    untagged = []
    n_tags = 0
    for setname in WORLD_SETS:
        data = load_json(TILESETS_DIR / f"{setname}.json")
        tags = {t.get("id"): t.get("palette") for t in data.get("tiles", [])}
        vram_ids = [v["tile"] for v in (data.get("vram_block") or {}).get("tiles", [])
                    if "tile" in v]
        for tid in sorted(set(vram_ids)):
            tag = tags.get(tid)
            if not isinstance(tag, str):
                untagged.append((setname, tid))
                continue
            n_tags += 1
            entry = ramps.get(tag)
            if entry is None:
                findings.append(
                    f"{setname}: tile '{tid}' tags unknown ramp '{tag}' "
                    f"(nearest slotted ramp wins; fix the tag)")
            elif not any(s.startswith(f"{setname}:") for s in entry.get("slots", [])):
                findings.append(
                    f"{setname}: tile '{tid}' tags ramp '{tag}' which holds no "
                    f"slot in set '{setname}' (slots: "
                    f"{','.join(entry.get('slots', [])) or 'NONE'}; "
                    f"nearest slotted ramp wins instead)")
    return findings, untagged, n_tags


def check_sprite_tags(exp):
    """Enemy/hero overworld.palette string tags (int slots pass through)."""
    ramps = exp["ramps"]
    findings = []
    n_tags = 0
    paths = sorted((REPO_ROOT / "screens" / "enemy_types").glob("*.json"))
    paths.append(REPO_ROOT / "screens" / "hero.json")
    for path in paths:
        data = load_json(path)
        ow = data.get("overworld") or {}
        pal = ow.get("palette", 0)
        if not isinstance(pal, str):
            continue
        n_tags += 1
        entry = ramps.get(pal)
        if entry is None:
            findings.append(f"{path.name}: overworld.palette '{pal}' is not a known ramp")
        elif not any(s.startswith("obj:") for s in entry.get("slots", [])):
            findings.append(f"{path.name}: overworld.palette '{pal}' holds no OBJ slot "
                            f"(slots: {','.join(entry.get('slots', [])) or 'NONE'})")
    return findings, n_tags


def check_combat_tags(exp):
    """combat_art palette (BG stamp should be base-slotted) / obj_palette
    + obj_alt_palette (OAM: slotless by design, existence only)."""
    ramps = exp["ramps"]
    findings = []
    n_tags = 0
    for path in sorted((REPO_ROOT / "screens" / "combat_art").glob("*.json")):
        data = load_json(path)
        sid = data.get("id", path.stem)
        pal = data.get("palette")
        if pal is not None:
            n_tags += 1
            entry = ramps.get(pal)
            if entry is None:
                findings.append(f"combat_art/{sid}: palette '{pal}' is not a known ramp")
            elif not data.get("oam") and not any(
                    s.startswith("base:") for s in entry.get("slots", [])):
                findings.append(f"combat_art/{sid}: BG-stamp palette '{pal}' holds no "
                                f"base slot (slots: "
                                f"{','.join(entry.get('slots', [])) or 'NONE'})")
        for key in ("obj_palette", "obj_alt_palette"):
            val = data.get(key)
            if val is not None:
                n_tags += 1
                if val not in ramps:
                    findings.append(f"combat_art/{sid}: {key} '{val}' is not a known ramp")
    return findings, n_tags


def mismatch_key(m):
    return (m.get("sheet"), tuple(m.get("tile") or []), m.get("declared"),
            m.get("used_ramp"), tuple(sorted(m.get("off_colors") or [])))


def check_freshness():
    """Committed export (+ public copy) matches a fresh render."""
    from palette_compiler import render_ramp_export
    want = render_ramp_export()
    errors = []
    for path in (EXPORT, EXPORT_PUBLIC):
        try:
            got = Path(path).read_text()
        except OSError as e:
            errors.append(f"{path}: unreadable ({e}); run `make manifest`")
            continue
        if got != want:
            errors.append(f"{path}: stale vs `make manifest` output; regenerate and commit")
    return errors


def check_budget():
    """Every current mismatch is allowlisted (no new fallbacks)."""
    if not MISMATCHES.exists():
        return [f"{MISMATCHES}: missing; run `make manifest` first"]
    if not ALLOWLIST.exists():
        return [f"{ALLOWLIST}: missing allowlist; seed it from current mismatches"]
    current = load_json(MISMATCHES)
    allowed_doc = load_json(ALLOWLIST)
    allowed = {mismatch_key(a) for a in allowed_doc.get("allow", [])}
    errors = []
    for m in current:
        if mismatch_key(m) not in allowed:
            errors.append(
                f"new ramp fallback: {m.get('sheet')} {m.get('tile')} "
                f"declared={m.get('declared')} used={m.get('used_ramp')} "
                f"off={','.join(m.get('off_colors') or [])} "
                f"({m.get('reason')}); repaint into the ramp or add to "
                f"assets/ramp_mismatch_allowlist.json")
    return errors


def main(argv):
    strict = "--strict" in argv
    try:
        exp = load_json(EXPORT)
        if "ramps" not in exp:
            raise ToolError(f"{EXPORT}: want 'ramps' object")
        findings = []
        wf, untagged, n_world = check_world_tags(exp)
        sf, n_sprites = check_sprite_tags(exp)
        cf, n_combat = check_combat_tags(exp)
        findings = wf + sf + cf
        for f in findings:
            print(f"ramp-tags report: {f}")
        print(f"ramp-tags: checked {n_world} world tags, {n_sprites} sprite tags, "
              f"{n_combat} combat tags "
              f"({len(findings)} advisory finding(s))")
        if not strict:
            return 0
        errors = [f"{s}: tile '{t}' has no palette tag "
                  f"(nearest slotted ramp wins silently; tag it explicitly)"
                  for s, t in untagged]
        errors += check_freshness()
        errors += check_budget()
        if errors:
            print("ramp-tags: STRICT FAILED", file=sys.stderr)
            for e in errors:
                print("  - " + e, file=sys.stderr)
            return 1
        print(f"ramp-tags: strict OK ({len(untagged)} untagged, "
              f"export fresh, mismatches allowlisted)")
        return 0
    except ToolError as e:
        print(f"ramp-tags: tool error: {e}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
