/* Generated by tools/png2gb.py from forest-tile.png (1 tile). */
const uint8_t forest_chest_sprite_tile[16] = {
    0x00, 0x00,   /*          */
    0x00, 0x00,   /*          */
    0x00, 0x00,   /*          */
    0x00, 0x00,   /*          */
    0x00, 0x00,   /*          */
    0x00, 0x00,   /*          */
    0x00, 0x00,   /*          */
    0x00, 0x00   /*          */
};
