/* Generated by tools/png2gb.py from forest-tile.png (1 tile). */
const uint8_t forest_chest_sprite_tile[16] = {
    0x00, 0x00,   /*          */
    0x00, 0x00,   /*          */
    0x00, 0x24,   /*   :  :   */
    0x42, 0x3C,   /*  .::::.  */
    0xDB, 0x7E,   /* .#:##:#. */
    0xC3, 0x7E,   /* .#::::#. */
    0xDB, 0x7E,   /* .#:##:#. */
    0x7E, 0x00   /*  ......  */
};
